### ISSUE TITLE
Missing CHANGELOG.md file

### ISSUE THREAD

**Issue by shalomtuby** [HelpHero/helphero-javascript#17]
Where can I find the change log report for this repository?
Without it, it will be hard to know if I can upgrade the package version safety.
Thanks 🙏 .

**Comment by cloudkite** [comment]
Hi @shalomtuby 

Sorry for the delay somehow we didn't get notified of this issue.

Please note we don't normally make breaking changes to the API.  However we follow semantic versioning see (https://semver.org/) so if we did we would increment the major version number so as long as it is a patch or minor version number you can assume theres no breaking changes and is fine to upgrade.

Let me know if you have any further questions on this. It might be quicker to get in touch via support@helphero.co

**Comment by thany** [comment]
Same question from me, seeing how the actual question wasn't answered. I'll ask a bit more clearly:

Where can we find the changelog please?
