### ISSUE TITLE
trouble building helphero-javascript using `npm install`

### ISSUE THREAD

**Issue by megahirt** [HelpHero/helphero-javascript#4]
Hi!

I am a HelpHero customer and am trying to debug a problem with importing HelpHero in our Typescript project.  In the process of debugging, I wanted to build this project using `npm install` and ran into the following issue which checking out the latest master.  My OS is Ubuntu 16.04  .  It appears that the Typescript is not compiling on master.  Here is the output:
```
vagrant@vag-u1604-xf:~/src/helphero-javascript (master)
$ npm install

> helphero@1.3.0 prepare /home/vagrant/src/helphero-javascript
> yarn tsc && yarn prettier-check && yarn clean && yarn build && yarn flowgen

yarn run v1.16.0
$ tsc --noEmit
src/helphero.ts:107:48 - error TS2345: Argument of type 'string[]' is not assignable to parameter of type '[string, ...unknown[]]'.
  Property '0' is missing in type 'string[]' but required in type '[string, ...unknown[]]'.

107       (window as _Window).HelpHero.apply(null, [method].concat(args));
                                                   ~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! helphero@1.3.0 prepare: `yarn tsc && yarn prettier-check && yarn clean && yarn build && yarn flowgen`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the helphero@1.3.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-06-11T09_03_32_211Z-debug.log

```

Should I be able to build this from master using `npm install`, assuming I have yarn installed?

**Comment by cloudkite** [comment]
Hi @megahirt,

Thanks for getting in touch. You will need todo an install via `yarn` rather than `npm install` otherwise it wont use the yarn.lock and therefore will not install the specific version of typescript it needs to build.

**Comment by megahirt** [comment]
Thank you!  I did a `yarn install` using the latest stable yarn (1.16) on Ubuntu 16.04 and it succeeded in building
