### ISSUE TITLE
Can you guys export the typescript types?

### ISSUE THREAD

**Issue by benwinding** [HelpHero/helphero-javascript#9]
Exporting the types, allows us to use the API in our typescript project. 

Here's the modification necessary to use your types.
![Peek 2020-05-01 16-23](https://user-images.githubusercontent.com/11782590/80788414-2e04ad80-8bc8-11ea-9a04-ed1fd1fbe71d.gif)

I'll make a pull request for it, if that's cool?!

**Comment by cloudkite** [comment]
@benwinding Its already possible to grab the main type using the utility method ReturnType see

```
import initHelpHero from 'helphero'
type HelpHero = ReturnType<typeof initHelpHero>
```

**Comment by benwinding** [comment]
Wow :eyes: what kind of magic is that!

Yeah that solves my problem and future problems!
